cancoesescritas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('songs/', include('songs.urls')),
    path('admin/', admin.site.urls),
]

songs/urls.py
from django.urls import path

from . import views

app_name = 'songs'
urlpatterns = [
    # path('', views.ListView, name='list'),
    # path('create/', views.CreateView, name='create'),
    # path('<int:post_id>/', views.DetailView, name='detail'),
    # path('update/<int:post_id>/', views.UpdateView, name='update'),
    # path('delete/<int:post_id>/', views.DeleteView, name='delete'),
    # path('', views.postFormListView.as_view(), name='list'),
    # path('<int:pk>/', views.postFormDetailView.as_view(), name='detail'),
    # path('create/', views.postFormCreateView.as_view(), name='create'),
    # path('update/<int:pk>/', views.postFormUpdateView.as_view(), name='update'),
    # path('delete/<int:pk>/', views.postFormDeleteView.as_view(), name='delete'),
    path('', views.postListView.as_view(), name='list'),
    path('<int:pk>/', views.postDetailView.as_view(), name='detail'),
    path('create/', views.postCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.postUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.postDeleteView.as_view(), name='delete'),
    path('search/', views.SearchView, name='search'),
    path('<int:post_id>/comment/', views.commentCreateView, name='comment'),
    path('categorys/', views.categoryListView.as_view(), name='categorys'),
    path('categorys/<int:pk>/', views.categoryDetailView.as_view(), name='detail-category'),
    path('categorys/create', views.categoryCreateView.as_view(), name='create-category'),
]

songs/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    title = models.CharField(max_length=255)
    artist = models.CharField(max_length=255)
    album = models.CharField(max_length=255)
    year = models.IntegerField()
    cover = models.URLField(max_length=200, null=True)
    lyrics = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.artist} - {self.title} ({self.year})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'
    
class Category(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    description = models.TextField()
    songs = models.ManyToManyField(Post)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}: {self.description} by {self.author}'

songs/forms.py
from django.forms import ModelForm
from .models import Post, Comment

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'artist',
            'album',
            'year',
            'cover',
            'lyrics',
        ]
        labels = {
            'title': 'Título',
            'artist': 'Artista',
            'album': 'Álbum',
            'year': 'Ano',
            'cover': 'Capa',
            'lyrics': 'Letra',
        }
        
class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

songs/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from .models import Post, Comment, Category
from .forms import PostForm, CommentForm
from django.urls import reverse, reverse_lazy
from django.views import generic
    
    
    
# def ListView(request):
#     post_list = Post.objects.all()
#     return render(request, 'songs/list.html', {'post_list': post_list})

# def DetailView(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)
#     return render(request, 'songs/detail.html', {'post': post})

# def CreateView(request):
#     if request.method == 'POST':
#         post_title = request.POST['title']
#         post_artist = request.POST['artist']
#         post_album = request.POST['album']
#         post_year = request.POST['year']
#         post_cover = request.POST['cover']
#         post_lyrics = request.POST['lyrics']
#         post = Post(title=post_title,
#                       artist=post_artist,
#                       album=post_album,
#                       year=post_year,
#                       cover=post_cover,
#                       lyrics=post_lyrics)
#         post.save()
#         return HttpResponseRedirect(
#             reverse('songs:detail', args=(post.id, )))
#     else:
#         return render(request, 'songs/create.html', {})
    
# def UpdateView(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if request.method == "POST":
#         post.title = request.POST['title']
#         post.artist = request.POST['artist']
#         post.album = request.POST['album']
#         post.year = request.POST['year']
#         post.cover = request.POST['cover']
#         post.lyrics = request.POST['lyrics']
#         post.save()
#         return HttpResponseRedirect(
#             reverse('songs:detail', args=(post.id, )))

#     context = {'post': post}
#     return render(request, 'songs/update.html', context)

# def DeleteView(request, post_id):
#     post = get_object_or_404(Post, pk=post_id)

#     if request.method == "POST":
#         post.delete()
#         return HttpResponseRedirect(reverse('songs:list'))

#     context = {'post': post}
#     return render(request, 'songs/delete.html', context)

# class postFormListView(generic.ListView):
#     model = Post
#     template_name = 'songs/list.html'

    
# class postFormDetailView(generic.DetailView):
#     model = Post
#     template_name = 'songs/detail.html'

# class postFormCreateView(generic.CreateView):
#     model = Post
#     template_name = 'songs/create.html'
#     fields = ['title', 'artist', 'album', 'year', 'cover', 'lyrics']
#     def get_success_url(self):
#         return reverse('songs:detail', kwargs={'pk': self.object.pk})

# class postFormUpdateView(generic.UpdateView):
#     model = Post
#     form_class = PostForm
#     template_name = 'songs/update.html'
#     def get_success_url(self):
#         return reverse('songs:detail', kwargs={'pk': self.object.pk})

# class postFormDeleteView(generic.DeleteView):
#     model = Post
#     template_name = 'songs/delete.html'
#     success_url = reverse_lazy('songs:list')
    

class postListView(generic.ListView):
    model = Post
    template_name = 'songs/list.html'
    
class postDetailView(generic.DetailView):
    model = Post
    template_name = 'songs/detail.html'
    
class postCreateView(generic.CreateView):
    model = Post
    template_name = 'songs/create.html'
    fields = ['title', 'artist', 'album', 'year', 'cover', 'lyrics']
    def get_success_url(self):
        return reverse('songs:detail', kwargs={'pk': self.object.pk})
    
class postUpdateView(generic.UpdateView):
    model = Post
    template_name = 'songs/update.html'
    fields = ['title', 'artist', 'album', 'year', 'cover', 'lyrics']
    def get_success_url(self):
        return reverse('songs:detail', kwargs={'pk': self.object.pk})
    
class postDeleteView(generic.DeleteView):
    model = Post
    template_name = 'songs/delete.html'
    def get_success_url(self):
        return reverse('songs:list')
    

def SearchView(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        post_list = Post.objects.filter(title__icontains=search_term)
        context = {"post_list": post_list}
    return render(request, 'songs/search.html', context)

def commentCreateView(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_author = form.cleaned_data['author']
            comment_text = form.cleaned_data['text']
            comment = Comment(author=comment_author,
                            text=comment_text,
                            post=post)
            comment.save()
            return HttpResponseRedirect(
                reverse('songs:detail', args=(post_id, )))
    else:
        form = CommentForm()
    context = {'form': form, 'post': post}
    return render(request, 'songs/create_comment.html', context)


class categoryListView(generic.ListView):
    model = Category
    template_name = 'songs/categorys.html'
    
class categoryDetailView(generic.DetailView):
    model = Category
    template_name = 'songs/detail_category.html'
    
class categoryCreateView(generic.CreateView):
    model = Category
    template_name = 'songs/create_category.html'
    fields = ['name', 'description', 'author', 'songs']
    success_url = reverse_lazy('songs:categorys')

songs/templates/songs/categorys.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias de músicas</h2>

<section>
    {% for category in category_list %}
    <hr>
    <article>
        <header>
            <a href="{% url 'songs:detail-category' category.id %}">
                <h3>{{category.name}} (de {{ category.author }}) </h3>
            </a>
        </header>
    </article>
    {% endfor %}

    <a href="{% url 'songs:create-category' %}"><button>Crie sua categoria</button></a>
</section>

{% endblock content %}

songs/templates/songs/create.html
{% extends 'base.html' %} {% block content %}
<h2>Inserir nova música</h2>
<form method="POST" action="{% url 'songs:create' %}">
  {% csrf_token %}
  <p>
    <label for="id_title">Título:</label>
    <input type="text" name="title" id="id_title" />
  </p>
  <p>
    <label for="id_artist">Artista:</label>
    <input type="text" name="artist" id="id_artist" />
  </p>
  <p>
    <label for="id_album">Álbum:</label>
    <input type="text" name="album" id="id_album" />
  </p>
  <p>
    <label for="id_year">Ano de lançamento:</label>
    <input type="number" name="year" id="id_year" />
  </p>
  <p>
    <label for="id_cover">URL da capa:</label>
    <input type="url" name="cover" id="id_cover" />
  </p>
  <p>
    <label for="id_lyrics">Letra:</label>
    <input type="text" name="lyrics" id="id_lyrics" />
  </p>
  <button type="submit">Criar</button>
</form>
{% comment %} <form action="{% url 'songs:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Inserir nova música</button>
</form> {% endcomment %}

{% endblock content %}

songs/templates/songs/create_category.html
{% extends 'base.html' %}

{% block title %}
Criar música
{% endblock title %}

{% block content %}
<h2>Criar categoria</h2>

<form action="{% url 'songs:create-category' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

songs/templates/songs/create_comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Fazer comentário sobre {{ post.title }} ({{ post.year }})</h2>

<form action="{% url 'songs:comment' post.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Postar comentário</button>
</form>

<p><a href="{% url 'songs:detail' post.id %}">Voltar para a página da música</a></p>
{% endblock content %}

songs/templates/songs/delete.html
{% extends 'base.html' %}
{% block content %}
<form action="{% url 'songs:delete' post.id %}" method="post">
  {% csrf_token %}
  <p>
    Você tem certeza que deseja apagar a música "{{ post.title }} ({{ post.year }})"?
  </p>
  <button type="submit">Apagar</button>
</form>
{% endblock content %}

songs/templates/songs/detail.html
{% extends 'base.html' %} {% block title %} {{ post.title }}
    {{ post.year }} {% endblock title %} {% block content %}
    <h2>Detalhes da música {{ post.title }} ({{ post.year }})</h2>
    
    <section class="dados-de-música">
      <img src="{{ post.cover }}" alt="Capa do título {{ post.title }}" />
      <ul>
        <li>Álbum: {{ post.album }}</li>
        <li>Ano de lançamento: {{ post.year }}</li>
        <li><a href="{% url 'songs:update' post.id %}">Editar</a></li>
        <li><a href="{% url 'songs:delete' post.id %}">Apagar</a></li>
      </ul>
        {% if post.category_set.all %}
            <h3>Inclusa nas categorias: </h3>
            <ul>
            {% for category in post.category_set.all %}
              <a href="{% url 'songs:detail-category' category.id %}">
                <li>{{ category.name }}</li>
              </a>
            {% endfor %}
            </ul>
        {% endif %}
    </section>

    <main>
      <h3>Letra</h3>
      <p>{{ post.lyrics }}</p>
    </main>

    <hr>

    <section>
      <header>
          <h3>Comentários</h3>
      </header>
      <ul>
          {% if post.comment_set.all %}
              {% for comment in post.comment_set.all|dictsortreversed:'date' %}
                  <figure>
                      <blockquote>
                          "{{ comment.text }}"
                      </blockquote>
                      <figcaption>—{{ comment.author }}, {{comment.date}}</figcaption>
                  </figure>
              {% endfor %}
          {% else %}
              <p>Ainda não existe nenhuma comentário para esta música.</p>
          {% endif %}
      </ul>

      <hr>

    <a href="{% url 'songs:comment' post.pk %}"><button>Crie seu comentário</button></a>
  </section>
    
    {% endblock content %}

songs/templates/songs/detail_category.html
{% extends 'base.html' %} {% block title %} {{ category.name }}
    {{ category.author }} {% endblock title %} {% block content %}
    <h2>Detalhes da categoria {{ category.name }}: {{ category.description }} - {{ category.author }}</h2>
    
    <section>
        <div class="lista-de-cards">
            {% for post in category.songs.all %}
                <div class="card">
                    <a href="{% url 'songs:detail' post.id %}">
                        <img src="{{ post.cover }}" alt="Capa do título {{ post.title }}">
                    </a>
                    <p>{{ post.title }} ({{ post.year }})</p>
                </div>
            {% endfor %}
        </div>
    </section>

    {% endblock content %}

songs/templates/songs/list.html
{% extends 'base.html' %} {% block content %}
<h2>Todas as músicas</h2>
<section>
  <p>
    Muitos resultados? <a href="{% url 'songs:search' %}">Buscar músicas</a>
  </p>
  <p>
    Não encontrou a música?
    <a href="{% url 'songs:create' %}">Adicionar nova música</a>
  </p>
</section>
{% if post_list %}
<section class="lista-de-cards">
  {% for post in post_list %}
  <article class="card">
    <a href="{% url 'songs:detail' post.id %}">
      <img src="{{ post.cover }}" alt="Capa do título {{ post.album }}"
    /></a>
    <p>{{ post.title }} ({{ post.year }})</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma música.</p>
{% endif %} {% endblock content %}

songs/templates/songs/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de músicas por título</h2>
<form action="{% url 'songs:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da busca</h2>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'songs:detail' post.id %}">
            <img src="{{ post.cover }}" alt="Capa do título {{ post.album }}"
        /></a>
        <p>{{ post.title }} ({{ post.year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrada nenhuma música para a busca.</p>
{% endif %}

{% endblock content %}

songs/templates/songs/update.html
{% extends 'base.html' %}
{% block content %}
<h2>Atualizar dados da música {{ post.title }} ({{ post.year}})</h2>
<form method="post" action="{% url 'songs:update' post.id%}">
  {% csrf_token %}
  <p>
    <label for="id_title">Título:</label>
    <input type="text" name="title" id="id_title" value="{{post.title}}" />
  </p>
  <p>
    <label for="id_artist">Artista:</label>
    <input type="text" name="artist" id="id_artist" value="{{post.artist}}" />
  </p>
  <p>
    <label for="id_album">Álbum:</label>
    <input type="text" name="album" id="id_album" value="{{post.album}}" />
  </p>
  <p>
    <label for="id_year">Ano de lançamento:</label>
    <input type="number" name="year" id="id_year" value="{{post.year}}" />
  </p>
  <p>
    <label for="id_cover">URL da capa:</label>
    <input type="url" name="cover" id="id_cover" value="{{post.cover}}" />
  </p>
  <p>
    <label for="id_lyrics">Letra:</label>
    <input type="text" name="lyrics" id="id_lyrics" value="{{post.lyrics}}" />
  </p>
  <button type="submit">Atualizar</button>
</form>

{% comment %} <form action="{% url 'songs:update' post.id%}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Atualizar</button>
</form> {% endcomment %}

{% endblock content %}