cancoesescritas/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('songs/', include('songs.urls')),
    path('admin/', admin.site.urls),
]

songs/urls.py
from django.urls import path

from . import views

app_name = 'songs'
urlpatterns = [
    # path('', views.ListView, name='list'),
    # path('create/', views.CreateView, name='create'),
    # path('<int:post_id>/', views.DetailView, name='detail'),
    # path('update/<int:post_id>/', views.UpdateView, name='update'),
    # path('delete/<int:post_id>/', views.DeleteView, name='delete'),
    # path('', views.postFormListView.as_view(), name='list'),
    # path('<int:pk>/', views.postFormDetailView.as_view(), name='detail'),
    # path('create/', views.postFormCreateView.as_view(), name='create'),
    # path('update/<int:pk>/', views.postFormUpdateView.as_view(), name='update'),
    # path('delete/<int:pk>/', views.postFormDeleteView.as_view(), name='delete'),
    path('', views.postListView.as_view(), name='list'),
    path('<int:pk>/', views.postDetailView.as_view(), name='detail'),
    path('create/', views.postCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.postUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.postDeleteView.as_view(), name='delete'),
    path('search/', views.SearchView, name='search'),
    path('<int:post_id>/comment/', views.commentCreateView, name='comment'),
    path('categorys/', views.categoryListView.as_view(), name='categorys'),
    path('categorys/<int:pk>/', views.categoryDetailView.as_view(), name='detail-category'),
    path('categorys/create', views.categoryCreateView.as_view(), name='create-category'),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}{% endblock %} | Canções escritas </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header class="header">
        <h1> <a href="{% url 'index' %}"> <font face="Cambria">Cancoes escritas</font> </a> </h1>
        <nav>
            <li><a href="{% url 'songs:list' %}">Músicas</a></li>
            <li><a href="{% url 'songs:categorys' %}">Categorias</a></li>
            <li><a href="{% url 'about' %}">Sobre o site</a></li>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock content %}
    </main>
    <footer>
        <small> &copy; 2023 by Fabio Baptista</small>
    </footer>
</body>

</html>